<!DOCTYPE html>
<html>
<head>
	
	<meta charset="utf-8">

</head>
<body>

	<div id="container"><!-- Início container -->
		
		<header><!-- Início header -->
			<div id="logo">
				<h1><a href="">Museu Nacional</a></h1>
			</div>

			<nav><!-- Início nav -->
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">Exposições</a></li>
			        <li><a href="#">Pesquisa</a></li>
			        <li><a href="#">Acervo</a></li>
			        <li><a href="#">vídeos</a></li>
			        <li><a href="#">fotos</a></li>
			        <li><a href="#">contato</a></li>
				</ul>
			</nav><!--/fim nav -->

		</header><!--/fim header -->

		<div id="principal"><!-- Início principal -->

						<div class="container">
			  <div class="d-flex justify-content-center mt-5">
			    <div class="card" style="width: 36rem;">
			      <div class="card-body">

			        <div class="d-flex justify-content-center">
			          <img src="/img/twitter_logo.png" />
			        </div>

			        <div class="row">
			          <div class="col">
			            <h2>Crie sua conta</h2>
			          </div>
			        </div>

			        <div class="row">
			          <div class="col">
			            
			            <form action="" method="post">
			              <div class="form-group">
			                <input type="text" class="form-control" placeholder="Nome">
			              </div>
			              
			              <div class="form-group">
			                <input type="text" class="form-control" placeholder="E-mail">
			              </div>

			              <div class="form-group">
			                <input type="password" class="form-control" placeholder="Senha">
			              </div>
			              
			              <div class="mt-4 mb-4">
			                <small class="form-text">
			                  Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido · Opções de Privacidade
			                </small>
			              </div>
			              <button type="submit" class="btn btn-primary btn-block">Inscrever-se</button>
			            </form>

			          </div>
			        </div>

			      </div>
			    </div>
			  </div>
			</div>

					<footer>
						<p>
							<a href="#">home</a>
				            <a href="#">Exposições</a>
				            <a href="#">Pesquisa</a>
				            <a href="#">acervo</a>
				            <a href="#">vídeos</a>
				            <a href="#">fotos</a>
				            <a href="#">contato</a>
						</p>
						<p>
							2019 <a href="">Museu Nacional</a> - Todos os direitos reservados.
						</p>
					</footer>

		</div><!--/fim principal -->

	</div><!--/fim container -->



</body>
</html>